const mahabharatQuotes = [
  "Dharma protects those who protect it; those who destroy dharma are destroyed. – Bhishma",
  "The greatest miracle is to be alive, yet people take it for granted. – Vidura",
  "Anger leads to delusion, and delusion destroys memory. – Krishna",
  "The greatest charity is to embrace peace and give up aggression. – Yudhishthira",
  "The mind is difficult to control, but it can be mastered through practice. – Krishna",
  "Only one free from selfishness attains true freedom. – Bhishma",
  "A king must protect his people like a father, not exploit them like a thief. – Vidura",
  "The root of all suffering is attachment. – Krishna",
  "Forgiveness is the highest virtue; it is the strength of the strong. – Draupadi",
  "Desire is the fire that burns the soul; only detachment can extinguish it. – Vidura",
  "Life is a balance between holding on and letting go. – Bhishma",
  "The greatest warrior is one who conquers his own anger. – Yudhishthira",
  "The world is a stage, and we are all actors in the drama of life. – Krishna",
  "True strength lies in self-control, not in dominating others. – Arjuna",
  "The path of dharma is subtle, but it leads to eternal peace. – Bhishma",
  "A single moment of righteousness can erase a lifetime of sin. – Yudhishthira",
  "The battlefield of the mind is fiercer than any war fought with weapons. – Arjuna",
  "The world is a reflection of your mind; purify it, and you will see the divine. – Krishna",
  "The greatest courage is to face the truth about oneself. – Arjuna",
  "The greatest wealth is contentment; the greatest poverty is greed. – Yudhishthira",
  "The mind is the cause of both bondage and liberation; master it, and you are free. – Krishna",
  "The greatest sacrifice is to give up personal desires for the sake of others. – Yudhishthira",
  "The world is sustained by the actions of the righteous. – Bhishma",
  "The greatest gift is knowledge, for it leads to liberation. – Vidura",
  "Victory and defeat are the same to the wise, for they are unattached to outcomes. – Bhishma",
  "The purpose of the soul’s journey is to awaken to its divine nature. – Krishna",
  "The mind is like a river; if uncontrolled, it causes destruction. – Vidura",
  "The greatest victory is the victory over one’s own mind. – Krishna",
  "One who is devoted to truth is a true warrior. – Yudhishthira",
  "One who is free from malice and ego is dear to the divine. – Krishna",
  "The world is a dream, and only the awakened soul sees its true nature. – Krishna",
  "The greatest wisdom is to know that you are not the body, but the soul. – Krishna",
  "The path of righteousness is like walking on a razor’s edge. – Bhishma",
  "The greatest strength is to remain calm in the face of adversity. – Draupadi",
  "Experience is the greatest teacher, and humility is the greatest lesson. – Vidura",
  "The world is a battlefield, and the true warrior fights for truth. – Arjuna",
  "The greatest battle is the one fought within, against the ego. – Arjuna",
  "The greatest sin is to betray one’s own conscience. – Yudhishthira",
  "One who is compassionate to all beings is a true sage. – Krishna",
  "The greatest joy is to live in harmony with one’s own dharma. – Bhishma",
  "A life lived in righteousness is the greatest legacy. – Yudhishthira",
  "One who sees the divine in all beings attains true wisdom. – Krishna",
  "Selfless service is the highest dharma. – Bhishma",
  "The mind is the source of all suffering; control it, and you find peace. – Krishna",
  "Standing for truth is the truest form of courage. – Arjuna",
  "Life is a journey, and dharma is its guide. – Yudhishthira",
  "Action performed with detachment leads to liberation. – Krishna",
  "A balanced mind always finds peace. – Bhishma",
  "One who sees the same soul in all beings overcomes fear. – Krishna",
  "One who walks the path of truth is always honored. – Yudhishthira",
  "When the mind is calm, the world appears peaceful. – Krishna",
  "The greatest war is the one fought within oneself. – Arjuna",
  "The path of dharma is difficult, but it leads to eternal victory. – Bhishma",
  "The power of truth is greater than any weapon. – Yudhishthira",
  "When the mind is pure, the divine is near. – Krishna",
  "One who sees all beings with equality is a true sage. – Bhishma",
  "One without self-control is his own enemy. – Vidura",
  "One who follows dharma is always protected. – Yudhishthira",
  "The mind is a wilderness; if not tamed, it will destroy you. – Krishna",
  "Truth and compassion are the pillars of a righteous life. – Yudhishthira",
  "The soul’s eternal nature is untouched by worldly changes. – Krishna",
  "The greatest honor is to live for the welfare of others. – Bhishma",
  "A disciplined mind is the key to liberation. – Krishna",
  "The true warrior fights not for glory, but for justice. – Arjuna",
  "The greatest wisdom is to act without attachment to results. – Krishna",
  "A righteous heart finds peace in any circumstance. – Yudhishthira",
  "The one who conquers desire conquers the world. – Bhishma",
  "Humility is the ornament of the wise. – Vidura",
  "The soul’s journey is to realize its unity with the divine. – Krishna",
  "The greatest strength is patience in the face of injustice. – Draupadi",
  "A life without dharma is like a ship without a rudder. – Bhishma",
  "The wise see no difference between friend and foe. – Krishna",
  "The greatest offering is a heart free from hatred. – Yudhishthira",
  "The mind, when purified, becomes a temple of the divine. – Krishna",
  "The true test of character is to remain just in adversity. – Arjuna",
  "Dharma is the foundation of a meaningful life. – Bhishma",
  "The one who lives for others lives for the divine. – Krishna",
  "The greatest knowledge is to understand the impermanence of the world. – Vidura",
  "A heart full of compassion is a heart full of divinity. – Krishna",
  "The true warrior is one who fights for the greater good. – Arjuna",
  "Righteousness is the shield that protects the soul. – Yudhishthira",
  "The mind is the creator of both joy and sorrow. – Krishna",
  "The greatest achievement is to live a life of truth. – Bhishma",
  "One who is free from envy finds true contentment. – Yudhishthira",
  "The divine resides in the heart of one who serves selflessly. – Krishna",
  "The path of truth is narrow, but it leads to liberation. – Bhishma",
  "The greatest gift is to inspire others to follow dharma. – Yudhishthira",
  "A calm mind is the abode of wisdom. – Krishna",
  "The true hero is one who overcomes his own flaws. – Arjuna",
  "The essence of life is to act with integrity. – Bhishma",
  "One who is kind to all beings is closest to the divine. – Krishna",
  "The greatest wealth is a heart free from desire. – Yudhishthira",
  "The mind is the battlefield where dharma and adharma clash. – Krishna",
  "The true purpose of life is to serve dharma. – Bhishma",
  "One who masters the self masters the world. – Krishna",
  "The greatest virtue is to remain truthful in all circumstances. – Yudhishthira",
  "The soul’s eternal light shines through a life of dharma. – Krishna",
  "The wise live not for themselves, but for the welfare of all. – Bhishma",
  "The greatest triumph is to live with a pure heart. – Yudhishthira"
];

export default mahabharatQuotes